books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.show, name='show'),
    path('add/', views.add, name='add'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

web_1210/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

# from books import views as book_views

# def root(request):
#     return redirect('books-index')
admin.site.site_title = 'Book 網站管理'
admin.site.site_header = 'Book 管理'


urlpatterns = [
    # django admin jet
    # https://github.com/geex-arts/django-jet


    path('', lambda request: redirect('books:index'), name='root'), # lambda=不具名變數
    path('books/', include('books.urls')),

    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
]

books/models.py
from django.db import models


class Book(models.Model):
    name = models.CharField('書名', max_length=20)
    price = models.PositiveIntegerField('價格')
    introduction = models.TextField('簡介')

    def __str__(self):
        return '{} ({})'.format(self.name, self.id)

books/forms.py
from django import forms

from .models import Book

#class BookForm(forms.Form):
#    name = forms.CharField(max_length=20, label="書名")
#    price = forms.IntegerField(min_value=1, label='價格')
#    introduction = forms.CharField(widget=forms.Textarea(), label='introduction')

class BookForm(forms.ModelForm):
    class Meta: # 從外部資料尋找
        model = Book
        #fields = ('name', 'introduction')
        fields = '__all__'

class DeleteConfirmForm(forms.Form):
    check = forms.BooleanField(label='你群定要刪除嗎？')

books/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from django.contrib import messages

from .forms import BookForm, DeleteConfirmForm
from .models import Book

def index(request):
    books = Book.objects.all()
    return render(request, 'books/index.html', {'books': books})

def show(request, pk):
    #try:
    #    book = Book.objects.get(pk=pk)
    #except Exception:
    #    raise Http404

    book = get_object_or_404(Book, pk=pk)

    return render(request, 'books/show.html', {'book': book})

def add(request):

    #if request.method == 'POST':
        # print(request.POST)

        #name = request.POST.get('name')
        #price = request.POST.get('price')
        #introduction = request.POST.get('introduction')

        #if not name:
        #    return render(request, 'books/add.html', {'message': 'name can not be bull'})

        #if not price.isdigit():
        #    pass

        #price = int(price)

        #if price <= 0:
        #    pass

        #if not introduction:
        #    pass

        #Book.objects.create(
        #    name=name,
        #    price=price,
        #    introduction=introduction,
        #)
    # form = None
    # if request.method == 'POST':
    #     form = BookForm(request.POST)
    #     if form.is_valid():
    #         Book.objects.create(**form.cleaned_data)
    #         #return render(request, 'books/add.html', {'message': 'create success'})
    #         #print(form.errors.get_json_data())
    #     #return render(request, 'books/add.html', {'message': form.errors.get_json_data()})
    # else:
    #     form = BookForm()
    # return render(request, 'books/add.html', {'form': form})

    form = BookForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request, '新增成功')
        return redirect('books:index') #重新導向回XX頁

    return render(request, 'books/add.html', {'form': form})


def edit(request, pk):
    book = get_object_or_404(Book, pk=pk)
    form = BookForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        messages.success(request, '更新成功')
        return redirect('books:index') #重新導向回XX頁

    return render(request, 'books/edit.html', {'form': form})


def delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    form = DeleteConfirmForm(request.POST or None)
    if form.is_valid() and form.cleaned_data['check']:
        book.delete()
        messages.success(request, '刪除成功')
        return redirect('books:index')

    return render(request, 'books/delete.html', {'form': form})
    # book.delete()
    # messages.success(request, '刪除成功')
    # return redirect('books:index')

web_1210/views.py
from django.http import HttpResponse
from django.shortcuts import render


def root(request):
    name = request.GET.get('name', 'guest')
    return HttpResponse('Hi, {}'.format(name))


def hello(request, name):
    return HttpResponse('Hi, {}'.format(name))


def s(request, number):
    return HttpResponse(number ** 2)


def l(request, number1, number2):
    step = -1 if number1 > number2 else 1
    _list = range(number1, number2+step, step)
    return render(request, 'l.html', {'list': _list})

templates/books/add.html
{% extends "layout.html" %}
{% load bootstrap4 %}

{% block main %}
    <div class="row">
        <div class="col">
            <h2>新增書籍</h2>
            {% include 'share/form.html'%}
        </div>
    </div>
{% endblock main %}

templates/books/delete.html
{% extends "layout.html" %}

{% block main %}
    <div class="row">
        <div class="col">
            <h2>刪除書籍</h2>
            {% include 'share/form.html'%}
        </div>
    </div>
{% endblock main %}

templates/books/edit.html
{% extends "layout.html" %}

{% block main %}
    <div class="row">
        <div class="col">
            <h2>更新書籍</h2>
            {% include 'share/form.html'%}
        </div>
    </div>
{% endblock main %}

templates/books/index.html
{% extends "layout.html" %}

{% block main %}

<div class="row">
    <div class="col">
        <a href="{% url 'books:add' %}" class="btn btn-outline-info float-right">Add book</a>
        <h2>Book List</h2>
        <hr>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>#</th>
                    <th>name</th>
                    <th>price</th>
                </tr>
            </thead>
            <tbody>
                {% for book in books %}
                    <tr>
                        <td>{{ book.id }}</td>
                        <!--/books/{{ book.id }}/-->
                        <td><a href="{% url 'books:show' book.id %}">{{ book.name }}</a></td>
                        <td>{{ book.price }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="3" class="text-center">No books!</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock main %}

templates/books/show.html
{% extends 'layout.html' %}

{% block main %}
    <h2>#{{ book.id }} {{ book.name }}</h2>
    <hr>
    <p>name:{{ book.name }}</p>
    <p>price:{{ book.price }}</p>
    <p>introduction:{{ book.introduction | linebreaksbr }}</p>

    <a href="{% url 'books:index' %}" class='btn btn-primary'><< Back</a>
    <a href="{% url 'books:edit' book.id %}" class='btn btn-info'>Edit</a>
    <a href="{% url 'books:delete' book.id %}" class='btn btn-danger'>Delete</a>
{% endblock main %}

templates/l.html
<ul>
  {% for i in list %}
    <li>{{ i }}</li>
  {% endfor %}
</ul>

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Book Store</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</head>

{% load bootstrap4 %}

<body>
    <div class="container my-3">
        <!--{% for message in messages %}
            {{ message }}
        {% endfor %}-->
        {% bootstrap_messages %}
        {% block main %}{% endblock %}
    </div>
</body>

</html>

templates/share/form.html
{% load bootstrap4 %}

<form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-outline-info float-right">Submit</button>
</form>